name: Docker CI/CD Pipeline

on:
  workflow_dispatch:
    branches:
      - main
      - master

env:
  DOCKER_BUILDKIT: 1

jobs:
  # -------------------------------------------------------------
  # Build jobs (for PR validation)
  # -------------------------------------------------------------
  build-node-codesign:
    name: Build (PR) - node-codesign
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      NODE_IMAGE_VERSION: 18
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build node-codesign (PR)
        run: |
          docker pull ghcr.io/${{ github.repository }}/node-codesign:${NODE_IMAGE_VERSION} || true
          docker build -f ./node-codesign/Dockerfile \
            --build-arg NODE_IMAGE_VERSION=${NODE_IMAGE_VERSION} \
            --cache-from ghcr.io/${{ github.repository }}/node-codesign:${NODE_IMAGE_VERSION} \
            --tag ghcr.io/${{ github.repository }}/node-codesign:${NODE_IMAGE_VERSION} ./node-codesign

  build-mono-nuget:
    name: Build (PR) - mono-nuget
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build mono-nuget (PR)
        run: |
          docker build -f ./mono-nuget/Dockerfile \
            --tag ghcr.io/${{ github.repository }}/mono-nuget ./mono-nuget

  build-net-framework-vs-workload:
    name: Build (PR) - net-framework-vs-workload
    runs-on: windows-latest
    if: github.event_name == 'pull_request'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build net-framework-vs-workload (PR)
        run: |
          docker pull ghcr.io/${{ github.repository }}/net-framework-vs-workload || echo "no cache"
          docker build -f ./net-framework-vs-workload/Dockerfile `
            --cache-from ghcr.io/${{ github.repository }}/net-framework-vs-workload `
            --tag ghcr.io/${{ github.repository }}/net-framework-vs-workload ./net-framework-vs-workload

  # -------------------------------------------------------------
  # Deploy jobs (only on default branch)
  # -------------------------------------------------------------
  deploy-node-codesign:
    name: Deploy node-codesign
    needs: build-node-codesign
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    strategy:
      matrix:
        node_version: [ "18.5.0", "18.19.0", "20.18.1", "20.19.2", "22.14.0" ]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push node-codesign (${{ matrix.node_version }})
        run: |
          docker pull ghcr.io/${{ github.repository }}/node-codesign:${{ matrix.node_version }} || true
          docker build -f ./node-codesign/Dockerfile \
            --build-arg NODE_IMAGE_VERSION=${{ matrix.node_version }} \
            --cache-from ghcr.io/${{ github.repository }}/node-codesign:${{ matrix.node_version }} \
            --tag ghcr.io/${{ github.repository }}/node-codesign:${{ matrix.node_version }} ./node-codesign
          docker push ghcr.io/${{ github.repository }}/node-codesign:${{ matrix.node_version }}

  deploy-mono-nuget:
    name: Deploy mono-nuget
    needs: build-mono-nuget
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push mono-nuget
        run: |
          docker build -f ./mono-nuget/Dockerfile --tag ghcr.io/${{ github.repository }}/mono-nuget ./mono-nuget
          docker push ghcr.io/${{ github.repository }}/mono-nuget

  deploy-net-framework-vs-workload:
    name: Deploy net-framework-vs-workload
    needs: build-net-framework-vs-workload
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push net-framework-vs-workload
        run: |
          docker pull ghcr.io/${{ github.repository }}/net-framework-vs-workload || echo "no cache"
          docker build -f ./net-framework-vs-workload/Dockerfile `
            --cache-from ghcr.io/${{ github.repository }}/net-framework-vs-workload `
            --tag ghcr.io/${{ github.repository }}/net-framework-vs-workload ./net-framework-vs-workload
          docker push ghcr.io/${{ github.repository }}/net-framework-vs-workload
